#!/usr/bin/env bash

set -e

TMP_FOLDER="$(mktemp -d)"
trap 'rm -rf -- "$TMP_FOLDER"' EXIT

find_python()
{
  for p in "$@"; do
    python=$(command -v $p)
    if [ -x "$python" ]; then
      major=$($python --version 2>&1 | cut -d" " -f2 | cut -d. -f1)
      if [[ $major == "3" ]]; then
        echo $python
        return 0
      fi
    fi
  done
}

python=$(find_python /usr/bin/python3 python3 python)
if [ -z "$python" ]; then
    >&2 echo "python3 is not available on this machine!"
    exit 1
fi

bstrap=src/pickley/bstrap.py
if [[ -x get-pickley && -f $bstrap ]]; then
  script=$bstrap
else
  script=$TMP_FOLDER/bstrap.py
  curl -fsSL -o "$script" "https://raw.githubusercontent.com/codrsquad/pickley/master/$bstrap"
fi

$python "$script" "$@"
