name: Release

on:
  push:
    tags:
      - 'v[0-9]*'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - run: pip install -U pip setuptools wheel twine tox
    - run: tox -e py,docs,style
    - run: python setup.py sdist bdist_wheel --universal

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Publish sdist and wheel
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PICKLEY }}
      run: twine upload dist/*
